type User @table {
  displayName: String!
  email: String!
  userType: String!
  photoUrl: String
  bio: String
}

type Course @table {
  title: String!
  courseCode: String!
  description: String
  startDate: Date
  endDate: Date
  instructor: User!
}

type Enrollment @table(key: ["student", "course"]) {
  student: User!
  course: Course!
  enrolledAt: Timestamp!
  grade: String
}

type Assignment @table {
  title: String!
  dueDate: Timestamp!
  assignmentType: String!
  description: String
  maxScore: Int
  course: Course!
}

type Submission @table {
  submittedAt: Timestamp!
  submissionUrl: String
  grade: String
  feedback: String
  assignment: Assignment!
  student: User!
}

type LearningResource @table {
  title: String!
  resourceType: String!
  content: String
  url: String
  filePath: String
  course: Course
  assignment: Assignment
  uploader: User
}